browser=chrome
url=https://google.com
timeout=10
headless=false
incognito=true
maximize=true
disableNotifications=true
remoteAllowOrigins=false
execution.mode=remote
grid.url=http://selenium-hub:4444/wd/hub
suiteXmlFile=testng.xml
